// <auto-generated />
namespace address_book_ggs_training.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RmUserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RmUserId));
        
        string IMigrationMetadata.Id
        {
            get { return "202006241607462_Rm-UserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
